[tools]
ruby = "latest"
node = "latest"
go = "latest"
python = "latest"
swiftformat = "latest"
swiftlint = "latest"
uv = "latest"

"npm:@openai/codex" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
